- namespace: pioneerNotification
  description: pioneerNotification

  functions:
  - name: enable
    type: function
    async: true
    description: Enables the participation notification
    parameters:
    - name: promptConfig
      type: any
      description: The prompt configuration

  events:
  - name: onShown
    type: function
    description: Fires when the participation prompt has been shown
    parameters: []
  - name: onAccept
    type: function
    description: Fires onAccept
    parameters: []
  - name: onLeaveStudy
    type: function
    description: Fires onLeaveStudy
    parameters: []
